Oppdaterer til spring boot 3
navikt/familie-ks-sak pull request #360
Opened 2023-06-11 23:26 UTC by UyQuangNguyen

Denne burde nok vært commit for commit, men det ble mye større enn jeg trodde.

Hva som er gjort:

- Oppdaterer til spring boot 3. Justeringer gjort slik at det fungerer.
- Oppdatering av dependencies
- Justering av kode, da oppdatering av dependencies førte til at Tilgang objektet ble annerledes.
- Justert på tester

2023-06-13 08:30 UTC, tnarland approved these changes
LGTM 🤩

2023-06-14 10:55 UTC, hensol approved these changes
🥇

2023-08-29 08:19 UTC, stigebil commented on build.gradle.kts
> +    val springdocVersion = "1.6.15"
Må oppgradere springdoc til 2.2.0 for at swagger skal funke med spring boot 3. Litt endringer i avhengigheter

 <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-common</artifactId>
            <version>${springdoc.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc.version}</version>
        </dependency>

2023-08-29 08:20 UTC, stigebil commented on build.gradle.kts
> +    val navFellesVersion = "2.20230210162649_a258d57-SPRING_BOOT_3"
Disse finnes nå i ikke SPRING_BOOT_3 versjon

2023-08-29 08:20 UTC, stigebil commented on build.gradle.kts
> +    val prosesseringVersion = "2.20230322091650_fb0187e-SPRING_BOOT_3"
Disse finnes nå i ikke SPRING_BOOT_3 versjon

2023-08-29 08:24 UTC, stigebil commented on build.gradle.kts
> +    val tokenValidationSpringVersion = "3.0.8"
3.1.4

2023-08-29 10:01 UTC, stigebil requested changes
springdoc må fikses

2023-08-30 07:33 UTC, stigebil approved these changes

2023-08-30 12:13 UTC, merged